export interface SubCategory {
    title: string
    href: string
}

export interface Category {
    title: string
    href?: string
    subcategories?: SubCategory[]
}

export const CATEGORIES_DATA: Category[] = [
    {
        title: "Cimento e Argamassas",
        subcategories: [
            { title: "Cimento CP II", href: "/categorias/cimento-e-argamassas/cimento-cp-ii" },
            { title: "Cimento CP III", href: "/categorias/cimento-e-argamassas/cimento-cp-iii" },
            { title: "Cimento CP IV", href: "/categorias/cimento-e-argamassas/cimento-cp-iv" },
            { title: "Cimento branco", href: "/categorias/cimento-e-argamassas/cimento-branco" },
            { title: "Argamassa AC1", href: "/categorias/cimento-e-argamassas/argamassa-ac1" },
            { title: "Argamassa AC2", href: "/categorias/cimento-e-argamassas/argamassa-ac2" },
            { title: "Argamassa AC3", href: "/categorias/cimento-e-argamassas/argamassa-ac3" },
            { title: "Argamassa para porcelanato", href: "/categorias/cimento-e-argamassas/argamassa-para-porcelanato" },
            { title: "Argamassa para piscina", href: "/categorias/cimento-e-argamassas/argamassa-para-piscina" },
            { title: "Argamassa refratária", href: "/categorias/cimento-e-argamassas/argamassa-refrataria" },
            { title: "Rejunte cimentício", href: "/categorias/cimento-e-argamassas/rejunte-cimenticio" },
            { title: "Rejunte acrílico", href: "/categorias/cimento-e-argamassas/rejunte-acrilico" },
            { title: "Rejunte epóxi", href: "/categorias/cimento-e-argamassas/rejunte-epoxi" },
            { title: "Massa pronta", href: "/categorias/cimento-e-argamassas/massa-pronta" },
            { title: "Massa para reboco", href: "/categorias/cimento-e-argamassas/massa-para-reboco" },
            { title: "Chapisco", href: "/categorias/cimento-e-argamassas/chapisco" },
            { title: "Gesso cola", href: "/categorias/cimento-e-argamassas/gesso-cola" },
            { title: "Cal hidratada", href: "/categorias/cimento-e-argamassas/cal-hidratada" },
            { title: "Cal virgem", href: "/categorias/cimento-e-argamassas/cal-virgem" },
            { title: "Areia fina ensacada", href: "/categorias/cimento-e-argamassas/areia-fina-ensacada" },
            { title: "Areia média ensacada", href: "/categorias/cimento-e-argamassas/areia-media-ensacada" },
            { title: "Areia grossa ensacada", href: "/categorias/cimento-e-argamassas/areia-grossa-ensacada" },
            { title: "Brita ensacada", href: "/categorias/cimento-e-argamassas/brita-ensacada" },
            { title: "Pedra para concreto", href: "/categorias/cimento-e-argamassas/pedra-para-concreto" },
            { title: "Aditivo plastificante", href: "/categorias/cimento-e-argamassas/aditivo-plastificante" },
            { title: "Aditivo impermeabilizante", href: "/categorias/cimento-e-argamassas/aditivo-impermeabilizante" },
            { title: "Aditivo acelerador", href: "/categorias/cimento-e-argamassas/aditivo-acelerador" },
            { title: "Aditivo retardador", href: "/categorias/cimento-e-argamassas/aditivo-retardador" },
            { title: "Mistura para contrapiso", href: "/categorias/cimento-e-argamassas/mistura-para-contrapiso" },
            { title: "Argamassa autonivelante", href: "/categorias/cimento-e-argamassas/argamassa-autonivelante" },
        ],
    },
    {
        title: "Tijolos e Blocos",
        subcategories: [
            { title: "Tijolo cerâmico 6 furos", href: "/categorias/tijolos-e-blocos/tijolo-ceramico-6-furos" },
            { title: "Tijolo cerâmico 8 furos", href: "/categorias/tijolos-e-blocos/tijolo-ceramico-8-furos" },
            { title: "Tijolo maciço", href: "/categorias/tijolos-e-blocos/tijolo-macico" },
            { title: "Bloco de concreto estrutural", href: "/categorias/tijolos-e-blocos/bloco-de-concreto-estrutural" },
            { title: "Bloco de concreto vedação", href: "/categorias/tijolos-e-blocos/bloco-de-concreto-vedacao" },
            { title: "Bloco canaleta", href: "/categorias/tijolos-e-blocos/bloco-canaleta" },
            { title: "Bloco celular", href: "/categorias/tijolos-e-blocos/bloco-celular" },
            { title: "Bloco sílico-calcário", href: "/categorias/tijolos-e-blocos/bloco-silico-calcario" },
            { title: "Tijolo ecológico", href: "/categorias/tijolos-e-blocos/tijolo-ecologico" },
            { title: "Meio bloco de concreto", href: "/categorias/tijolos-e-blocos/meio-bloco-de-concreto" },
            { title: "Bloco de vidro", href: "/categorias/tijolos-e-blocos/bloco-de-vidro" },
            { title: "Tijolo refratário", href: "/categorias/tijolos-e-blocos/tijolo-refratario" },
            { title: "Bloco de gesso", href: "/categorias/tijolos-e-blocos/bloco-de-gesso" },
            { title: "Tijolo aparente", href: "/categorias/tijolos-e-blocos/tijolo-aparente" },
            { title: "Placa cimentícia", href: "/categorias/tijolos-e-blocos/placa-cimenticia" },
            { title: "Divisória em bloco", href: "/categorias/tijolos-e-blocos/divisoria-em-bloco" },
            { title: "Bloco para muro", href: "/categorias/tijolos-e-blocos/bloco-para-muro" },
            { title: "Bloco para fundação", href: "/categorias/tijolos-e-blocos/bloco-para-fundacao" },
            { title: "Canaleta de concreto", href: "/categorias/tijolos-e-blocos/canaleta-de-concreto" },
            { title: "Bloco de amarração", href: "/categorias/tijolos-e-blocos/bloco-de-amarracao" },
            { title: "Bloco de canto", href: "/categorias/tijolos-e-blocos/bloco-de-canto" },
            { title: "Bloco compensador", href: "/categorias/tijolos-e-blocos/bloco-compensador" },
            { title: "Bloco para laje", href: "/categorias/tijolos-e-blocos/bloco-para-laje" },
            { title: "Tijolo para churrasqueira", href: "/categorias/tijolos-e-blocos/tijolo-para-churrasqueira" },
            { title: "Tijolo decorativo", href: "/categorias/tijolos-e-blocos/tijolo-decorativo" },
            { title: "Cobogó cerâmico", href: "/categorias/tijolos-e-blocos/cobogo-ceramico" },
            { title: "Cobogó de concreto", href: "/categorias/tijolos-e-blocos/cobogo-de-concreto" },
            { title: "Bloco vazado", href: "/categorias/tijolos-e-blocos/bloco-vazado" },
            { title: "Bloco acústico", href: "/categorias/tijolos-e-blocos/bloco-acustico" },
            { title: "Bloco térmico", href: "/categorias/tijolos-e-blocos/bloco-termico" },
        ],
    },
    {
        title: "Areia, Brita e Agregados",
        subcategories: [
            { title: "Areia fina", href: "/categorias/areia-brita-e-agregados/areia-fina" },
            { title: "Areia média", href: "/categorias/areia-brita-e-agregados/areia-media" },
            { title: "Areia grossa", href: "/categorias/areia-brita-e-agregados/areia-grossa" },
            { title: "Areia lavada", href: "/categorias/areia-brita-e-agregados/areia-lavada" },
            { title: "Areia de reboco", href: "/categorias/areia-brita-e-agregados/areia-de-reboco" },
            { title: "Areia de assentamento", href: "/categorias/areia-brita-e-agregados/areia-de-assentamento" },
            { title: "Pó de pedra", href: "/categorias/areia-brita-e-agregados/po-de-pedra" },
            { title: "Pedra brita 0", href: "/categorias/areia-brita-e-agregados/pedra-brita-0" },
            { title: "Pedra brita 1", href: "/categorias/areia-brita-e-agregados/pedra-brita-1" },
            { title: "Pedra brita 2", href: "/categorias/areia-brita-e-agregados/pedra-brita-2" },
            { title: "Pedra brita 3", href: "/categorias/areia-brita-e-agregados/pedra-brita-3" },
            { title: "Pedrisco", href: "/categorias/areia-brita-e-agregados/pedrisco" },
            { title: "Seixo rolado", href: "/categorias/areia-brita-e-agregados/seixo-rolado" },
            { title: "Cascalho", href: "/categorias/areia-brita-e-agregados/cascalho" },
            { title: "Rachão", href: "/categorias/areia-brita-e-agregados/rachao" },
            { title: "Pedra para drenagem", href: "/categorias/areia-brita-e-agregados/pedra-para-drenagem" },
            { title: "Pedra decorativa branca", href: "/categorias/areia-brita-e-agregados/pedra-decorativa-branca" },
            { title: "Pedra decorativa preta", href: "/categorias/areia-brita-e-agregados/pedra-decorativa-preta" },
            { title: "Pedra para jardim", href: "/categorias/areia-brita-e-agregados/pedra-para-jardim" },
            { title: "Terra vegetal", href: "/categorias/areia-brita-e-agregados/terra-vegetal" },
            { title: "Saibro", href: "/categorias/areia-brita-e-agregados/saibro" },
            { title: "Barro para aterro", href: "/categorias/areia-brita-e-agregados/barro-para-aterro" },
            { title: "Argila expandida", href: "/categorias/areia-brita-e-agregados/argila-expandida" },
            { title: "Sub-base", href: "/categorias/areia-brita-e-agregados/sub-base" },
            { title: "Material para concreto", href: "/categorias/areia-brita-e-agregados/material-para-concreto" },
            { title: "Material para contrapiso", href: "/categorias/areia-brita-e-agregados/material-para-contrapiso" },
            { title: "Bica corrida", href: "/categorias/areia-brita-e-agregados/bica-corrida" },
            { title: "Pedra moída", href: "/categorias/areia-brita-e-agregados/pedra-moida" },
            { title: "Granilha", href: "/categorias/areia-brita-e-agregados/granilha" },
            { title: "Agregado reciclado", href: "/categorias/areia-brita-e-agregados/agregado-reciclado" },
        ],
    },
    {
        title: "Ferragens e Aço",
        subcategories: [
            { title: "Vergalhão CA-50", href: "/categorias/ferragens-e-aco/vergalhao-ca-50" },
            { title: "Vergalhão CA-60", href: "/categorias/ferragens-e-aco/vergalhao-ca-60" },
            { title: "Arame recozido", href: "/categorias/ferragens-e-aco/arame-recozido" },
            { title: "Arame galvanizado", href: "/categorias/ferragens-e-aco/arame-galvanizado" },
            { title: "Tela soldada", href: "/categorias/ferragens-e-aco/tela-soldada" },
            { title: "Coluna armada", href: "/categorias/ferragens-e-aco/coluna-armada" },
            { title: "Estribo", href: "/categorias/ferragens-e-aco/estribo" },
            { title: "Treliça", href: "/categorias/ferragens-e-aco/trelica" },
            { title: "Perfil U", href: "/categorias/ferragens-e-aco/perfil-u" },
            { title: "Perfil L", href: "/categorias/ferragens-e-aco/perfil-l" },
            { title: "Barra chata", href: "/categorias/ferragens-e-aco/barra-chata" },
            { title: "Cantoneira", href: "/categorias/ferragens-e-aco/cantoneira" },
            { title: "Tubo metalon", href: "/categorias/ferragens-e-aco/tubo-metalon" },
            { title: "Chapa galvanizada", href: "/categorias/ferragens-e-aco/chapa-galvanizada" },
            { title: "Chapa lisa", href: "/categorias/ferragens-e-aco/chapa-lisa" },
            { title: "Chapa expandida", href: "/categorias/ferragens-e-aco/chapa-expandida" },
            { title: "Malha pop", href: "/categorias/ferragens-e-aco/malha-pop" },
            { title: "Prego com cabeça", href: "/categorias/ferragens-e-aco/prego-com-cabeca" },
            { title: "Prego sem cabeça", href: "/categorias/ferragens-e-aco/prego-sem-cabeca" },
            { title: "Prego para telha", href: "/categorias/ferragens-e-aco/prego-para-telha" },
            { title: "Prego para concreto", href: "/categorias/ferragens-e-aco/prego-para-concreto" },
            { title: "Parafuso sextavado", href: "/categorias/ferragens-e-aco/parafuso-sextavado" },
            { title: "Barra roscada", href: "/categorias/ferragens-e-aco/barra-roscada" },
            { title: "Porca", href: "/categorias/ferragens-e-aco/porca" },
            { title: "Arruela", href: "/categorias/ferragens-e-aco/arruela" },
            { title: "Tela para alambrado", href: "/categorias/ferragens-e-aco/tela-para-alambrado" },
            { title: "Tela mosquiteira metálica", href: "/categorias/ferragens-e-aco/tela-mosquiteira-metalica" },
            { title: "Corrente galvanizada", href: "/categorias/ferragens-e-aco/corrente-galvanizada" },
            { title: "Cabo de aço", href: "/categorias/ferragens-e-aco/cabo-de-aco" },
            { title: "Gancho metálico", href: "/categorias/ferragens-e-aco/gancho-metalico" },
        ],
    },
    {
        title: "Madeiras",
        subcategories: [
            { title: "Tábua de pinus", href: "/categorias/madeiras/tabua-de-pinus" },
            { title: "Tábua de eucalipto", href: "/categorias/madeiras/tabua-de-eucalipto" },
            { title: "Viga de madeira", href: "/categorias/madeiras/viga-de-madeira" },
            { title: "Caibro", href: "/categorias/madeiras/caibro" },
            { title: "Ripa", href: "/categorias/madeiras/ripa" },
            { title: "Sarrafo", href: "/categorias/madeiras/sarrafo" },
            { title: "Pontalete", href: "/categorias/madeiras/pontalete" },
            { title: "Compensado comum", href: "/categorias/madeiras/compensado-comum" },
            { title: "Compensado plastificado", href: "/categorias/madeiras/compensado-plastificado" },
            { title: "MDF cru", href: "/categorias/madeiras/mdf-cru" },
            { title: "MDF revestido", href: "/categorias/madeiras/mdf-revestido" },
            { title: "MDP", href: "/categorias/madeiras/mdp" },
            { title: "OSB", href: "/categorias/madeiras/osb" },
            { title: "Porta de madeira", href: "/categorias/madeiras/porta-de-madeira" },
            { title: "Batente de madeira", href: "/categorias/madeiras/batente-de-madeira" },
            { title: "Guarnição de madeira", href: "/categorias/madeiras/guarnicao-de-madeira" },
            { title: "Rodapé de madeira", href: "/categorias/madeiras/rodape-de-madeira" },
            { title: "Forro de madeira", href: "/categorias/madeiras/forro-de-madeira" },
            { title: "Deck de madeira", href: "/categorias/madeiras/deck-de-madeira" },
            { title: "Assoalho de madeira", href: "/categorias/madeiras/assoalho-de-madeira" },
            { title: "Madeira tratada", href: "/categorias/madeiras/madeira-tratada" },
            { title: "Prancha", href: "/categorias/madeiras/prancha" },
            { title: "Painel de madeira", href: "/categorias/madeiras/painel-de-madeira" },
            { title: "Lambril", href: "/categorias/madeiras/lambril" },
            { title: "Madeira para telhado", href: "/categorias/madeiras/madeira-para-telhado" },
            { title: "Madeira para forma", href: "/categorias/madeiras/madeira-para-forma" },
            { title: "Escora de madeira", href: "/categorias/madeiras/escora-de-madeira" },
            { title: "Taco de madeira", href: "/categorias/madeiras/taco-de-madeira" },
            { title: "Fechadura para porta de madeira", href: "/categorias/madeiras/fechadura-para-porta-de-madeira" },
            { title: "Selador para madeira", href: "/categorias/madeiras/selador-para-madeira" },
        ],
    },
    {
        title: "Telhas e Coberturas",
        subcategories: [
            { title: "Telha cerâmica", href: "/categorias/telhas-e-coberturas/telha-ceramica" },
            { title: "Telha de concreto", href: "/categorias/telhas-e-coberturas/telha-de-concreto" },
            { title: "Telha fibrocimento", href: "/categorias/telhas-e-coberturas/telha-fibrocimento" },
            { title: "Telha galvanizada", href: "/categorias/telhas-e-coberturas/telha-galvanizada" },
            { title: "Telha sanduíche", href: "/categorias/telhas-e-coberturas/telha-sanduiche" },
            { title: "Telha translúcida", href: "/categorias/telhas-e-coberturas/telha-translucida" },
            { title: "Cumeeira", href: "/categorias/telhas-e-coberturas/cumeeira" },
            { title: "Espigão", href: "/categorias/telhas-e-coberturas/espigao" },
            { title: "Rufo", href: "/categorias/telhas-e-coberturas/rufo" },
            { title: "Calha galvanizada", href: "/categorias/telhas-e-coberturas/calha-galvanizada" },
            { title: "Calha PVC", href: "/categorias/telhas-e-coberturas/calha-pvc" },
            { title: "Condutor de água", href: "/categorias/telhas-e-coberturas/condutor-de-agua" },
            { title: "Manta térmica", href: "/categorias/telhas-e-coberturas/manta-termica" },
            { title: "Manta aluminizada", href: "/categorias/telhas-e-coberturas/manta-aluminizada" },
            { title: "Subcobertura", href: "/categorias/telhas-e-coberturas/subcobertura" },
            { title: "Parafuso para telha", href: "/categorias/telhas-e-coberturas/parafuso-para-telha" },
            { title: "Vedante para telha", href: "/categorias/telhas-e-coberturas/vedante-para-telha" },
            { title: "Fixador de cumeeira", href: "/categorias/telhas-e-coberturas/fixador-de-cumeeira" },
            { title: "Selante para cobertura", href: "/categorias/telhas-e-coberturas/selante-para-cobertura" },
            { title: "Telha colonial", href: "/categorias/telhas-e-coberturas/telha-colonial" },
            { title: "Telha romana", href: "/categorias/telhas-e-coberturas/telha-romana" },
            { title: "Telha portuguesa", href: "/categorias/telhas-e-coberturas/telha-portuguesa" },
            { title: "Telha americana", href: "/categorias/telhas-e-coberturas/telha-americana" },
            { title: "Telha ecológica", href: "/categorias/telhas-e-coberturas/telha-ecologica" },
            { title: "Chapa trapezoidal", href: "/categorias/telhas-e-coberturas/chapa-trapezoidal" },
            { title: "Dome translúcido", href: "/categorias/telhas-e-coberturas/dome-translucido" },
            { title: "Exaustor eólico", href: "/categorias/telhas-e-coberturas/exaustor-eolico" },
            { title: "Claraboia", href: "/categorias/telhas-e-coberturas/claraboia" },
            { title: "Acessórios para calha", href: "/categorias/telhas-e-coberturas/acessorios-para-calha" },
            { title: "Suporte para calha", href: "/categorias/telhas-e-coberturas/suporte-para-calha" },
        ],
    },
    {
        title: "Impermeabilização",
        subcategories: [
            { title: "Manta asfáltica", href: "/categorias/impermeabilizacao/manta-asfaltica" },
            { title: "Manta líquida", href: "/categorias/impermeabilizacao/manta-liquida" },
            { title: "Vedapren", href: "/categorias/impermeabilizacao/vedapren" },
            { title: "Impermeabilizante flexível", href: "/categorias/impermeabilizacao/impermeabilizante-flexivel" },
            { title: "Impermeabilizante rígido", href: "/categorias/impermeabilizacao/impermeabilizante-rigido" },
            { title: "Selador acrílico", href: "/categorias/impermeabilizacao/selador-acrilico" },
            { title: "Fundo preparador", href: "/categorias/impermeabilizacao/fundo-preparador" },
            { title: "Hidrofugante", href: "/categorias/impermeabilizacao/hidrofugante" },
            { title: "Resina impermeabilizante", href: "/categorias/impermeabilizacao/resina-impermeabilizante" },
            { title: "Fita vedadora", href: "/categorias/impermeabilizacao/fita-vedadora" },
            { title: "Tela para impermeabilização", href: "/categorias/impermeabilizacao/tela-para-impermeabilizacao" },
            { title: "Primer asfáltico", href: "/categorias/impermeabilizacao/primer-asfaltico" },
            { title: "Membrana acrílica", href: "/categorias/impermeabilizacao/membrana-acrilica" },
            { title: "Argamassa polimérica", href: "/categorias/impermeabilizacao/argamassa-polimerica" },
            { title: "Cristalizante", href: "/categorias/impermeabilizacao/cristalizante" },
            { title: "Selante PU", href: "/categorias/impermeabilizacao/selante-pu" },
            { title: "Silicone de vedação", href: "/categorias/impermeabilizacao/silicone-de-vedacao" },
            { title: "Fita aluminizada", href: "/categorias/impermeabilizacao/fita-aluminizada" },
            { title: "Veda trinca", href: "/categorias/impermeabilizacao/veda-trinca" },
            { title: "Injetor de fissura", href: "/categorias/impermeabilizacao/injetor-de-fissura" },
            { title: "Vedante para laje", href: "/categorias/impermeabilizacao/vedante-para-laje" },
            { title: "Vedante para calha", href: "/categorias/impermeabilizacao/vedante-para-calha" },
            { title: "Vedante para telhado", href: "/categorias/impermeabilizacao/vedante-para-telhado" },
            { title: "Impermeabilizante para parede", href: "/categorias/impermeabilizacao/impermeabilizante-para-parede" },
            { title: "Impermeabilizante para piso", href: "/categorias/impermeabilizacao/impermeabilizante-para-piso" },
            { title: "Impermeabilizante para banheiro", href: "/categorias/impermeabilizacao/impermeabilizante-para-banheiro" },
            { title: "Impermeabilizante para piscina", href: "/categorias/impermeabilizacao/impermeabilizante-para-piscina" },
            { title: "Impermeabilizante para caixa d’água", href: "/categorias/impermeabilizacao/impermeabilizante-para-caixa-dagua" },
            { title: "Manta para baldrame", href: "/categorias/impermeabilizacao/manta-para-baldrame" },
            { title: "Vedação para junta", href: "/categorias/impermeabilizacao/vedacao-para-junta" },
        ],
    },
    {
        title: "Hidráulica",
        subcategories: [
            { title: "Tubo soldável", href: "/categorias/hidraulica/tubo-soldavel" },
            { title: "Tubo roscável", href: "/categorias/hidraulica/tubo-roscavel" },
            { title: "Tubo esgoto", href: "/categorias/hidraulica/tubo-esgoto" },
            { title: "Tubo drenagem", href: "/categorias/hidraulica/tubo-drenagem" },
            { title: "Joelho soldável", href: "/categorias/hidraulica/joelho-soldavel" },
            { title: "Tê soldável", href: "/categorias/hidraulica/te-soldavel" },
            { title: "Luva soldável", href: "/categorias/hidraulica/luva-soldavel" },
            { title: "Registro de gaveta", href: "/categorias/hidraulica/registro-de-gaveta" },
            { title: "Registro de pressão", href: "/categorias/hidraulica/registro-de-pressao" },
            { title: "Torneira de jardim", href: "/categorias/hidraulica/torneira-de-jardim" },
            { title: "Torneira de cozinha", href: "/categorias/hidraulica/torneira-de-cozinha" },
            { title: "Torneira de banheiro", href: "/categorias/hidraulica/torneira-de-banheiro" },
            { title: "Sifão", href: "/categorias/hidraulica/sifao" },
            { title: "Caixa sifonada", href: "/categorias/hidraulica/caixa-sifonada" },
            { title: "Ralo", href: "/categorias/hidraulica/ralo" },
            { title: "Válvula de pia", href: "/categorias/hidraulica/valvula-de-pia" },
            { title: "Caixa d’água", href: "/categorias/hidraulica/caixa-dagua" },
            { title: "Boia para caixa d’água", href: "/categorias/hidraulica/boia-para-caixa-dagua" },
            { title: "Conexão flange", href: "/categorias/hidraulica/conexao-flange" },
            { title: "Adaptador soldável", href: "/categorias/hidraulica/adaptador-soldavel" },
            { title: "União soldável", href: "/categorias/hidraulica/uniao-soldavel" },
            { title: "Curva de esgoto", href: "/categorias/hidraulica/curva-de-esgoto" },
            { title: "Tê de esgoto", href: "/categorias/hidraulica/te-de-esgoto" },
            { title: "Luva de correr", href: "/categorias/hidraulica/luva-de-correr" },
            { title: "Cola para PVC", href: "/categorias/hidraulica/cola-for-pvc" },
            { title: "Fita veda rosca", href: "/categorias/hidraulica/fita-veda-rosca" },
            { title: "Engate flexível", href: "/categorias/hidraulica/engate-flexivel" },
            { title: "Ducha higiênica", href: "/categorias/hidraulica/ducha-higienica" },
            { title: "Chuveiro", href: "/categorias/hidraulica/chuveiro" },
            { title: "Pressurizador", href: "/categorias/hidraulica/pressurizador" },
        ],
    },
    {
        title: "Elétrica",
        subcategories: [
            { title: "Fio rígido", href: "/categorias/eletrica/fio-rigido" },
            { title: "Cabo flexível", href: "/categorias/eletrica/cabo-flexivel" },
            { title: "Cabo PP", href: "/categorias/eletrica/cabo-pp" },
            { title: "Eletroduto PVC", href: "/categorias/eletrica/eletroduto-pvc" },
            { title: "Eletroduto corrugado", href: "/categorias/eletrica/eletroduto-corrugado" },
            { title: "Caixa 4x2", href: "/categorias/eletrica/caixa-4x2" },
            { title: "Caixa 4x4", href: "/categorias/eletrica/caixa-4x4" },
            { title: "Tomada simples", href: "/categorias/eletrica/tomada-simples" },
            { title: "Tomada dupla", href: "/categorias/eletrica/tomada-dupla" },
            { title: "Interruptor simples", href: "/categorias/eletrica/interruptor-simples" },
            { title: "Interruptor paralelo", href: "/categorias/eletrica/interruptor-paralelo" },
            { title: "Disjuntor monopolar", href: "/categorias/eletrica/disjuntor-monopolar" },
            { title: "Disjuntor bipolar", href: "/categorias/eletrica/disjuntor-bipolar" },
            { title: "Disjuntor tripolar", href: "/categorias/eletrica/disjuntor-tripolar" },
            { title: "Quadro de distribuição", href: "/categorias/eletrica/quadro-de-distribuicao" },
            { title: "Barramento", href: "/categorias/eletrica/barramento" },
            { title: "Conector elétrico", href: "/categorias/eletrica/conector-eletrico" },
            { title: "Fita isolante", href: "/categorias/eletrica/fita-isolante" },
            { title: "Terminal elétrico", href: "/categorias/eletrica/terminal-eletrico" },
            { title: "Lâmpada LED", href: "/categorias/eletrica/lampada-led" },
            { title: "Refletor LED", href: "/categorias/eletrica/refletor-led" },
            { title: "Plafon", href: "/categorias/eletrica/plafon" },
            { title: "Soquete", href: "/categorias/eletrica/soquete" },
            { title: "Sensor de presença", href: "/categorias/eletrica/sensor-de-presenca" },
            { title: "Campainha", href: "/categorias/eletrica/campainha" },
            { title: "Chuveiro elétrico", href: "/categorias/eletrica/chuveiro-eletrico" },
            { title: "Haste de aterramento", href: "/categorias/eletrica/haste-de-aterramento" },
            { title: "DPS", href: "/categorias/eletrica/dps" },
            { title: "DR", href: "/categorias/eletrica/dr" },
            { title: "Canaleta elétrica", href: "/categorias/eletrica/canaleta-eletrica" },
        ],
    },
    {
        title: "Iluminação",
        subcategories: [
            { title: "Lâmpada bulbo LED", href: "/categorias/iluminacao/lampada-bulbo-led" },
            { title: "Lâmpada tubular LED", href: "/categorias/iluminacao/lampada-tubular-led" },
            { title: "Lâmpada spot LED", href: "/categorias/iluminacao/lampada-spot-led" },
            { title: "Refletor LED", href: "/categorias/iluminacao/refletor-led" },
            { title: "Painel LED", href: "/categorias/iluminacao/painel-led" },
            { title: "Plafon de sobrepor", href: "/categorias/iluminacao/plafon-de-sobrepor" },
            { title: "Plafon embutido", href: "/categorias/iluminacao/plafon-embutido" },
            { title: "Arandela", href: "/categorias/iluminacao/arandela" },
            { title: "Lustre", href: "/categorias/iluminacao/lustre" },
            { title: "Pendente", href: "/categorias/iluminacao/pendente" },
            { title: "Trilho eletrificado", href: "/categorias/iluminacao/trilho-eletrificado" },
            { title: "Fita LED", href: "/categorias/iluminacao/fita-led" },
            { title: "Perfil para LED", href: "/categorias/iluminacao/perfil-para-led" },
            { title: "Driver para LED", href: "/categorias/iluminacao/driver-para-led" },
            { title: "Sensor de presença", href: "/categorias/iluminacao/sensor-de-presenca" },
            { title: "Fotocélula", href: "/categorias/iluminacao/fotocelula" },
            { title: "Luminária de emergência", href: "/categorias/iluminacao/luminaria-de-emergencia" },
            { title: "Balizador", href: "/categorias/iluminacao/balizador" },
            { title: "Luminária industrial", href: "/categorias/iluminacao/luminaria-industrial" },
            { title: "Luminária externa", href: "/categorias/iluminacao/luminaria-externa" },
            { title: "Luminária solar", href: "/categorias/iluminacao/luminaria-solar" },
            { title: "Poste decorativo", href: "/categorias/iluminacao/poste-decorativo" },
            { title: "Spot de jardim", href: "/categorias/iluminacao/spot-de-jardim" },
            { title: "Abajur técnico", href: "/categorias/iluminacao/abajur-tecnico" },
            { title: "Soquete", href: "/categorias/iluminacao/soquete" },
            { title: "Bocal adaptador", href: "/categorias/iluminacao/bocal-adaptador" },
            { title: "Controle para iluminação", href: "/categorias/iluminacao/controle-para-iluminacao" },
            { title: "Dimmer", href: "/categorias/iluminacao/dimmer" },
            { title: "Lâmpada decorativa", href: "/categorias/iluminacao/lampada-decorativa" },
            { title: "Luminária de teto", href: "/categorias/iluminacao/luminaria-de-teto" },
        ],
    },
    {
        title: "Louças Sanitárias",
        subcategories: [
            { title: "Vaso sanitário convencional", href: "/categorias/loucas-sanitarias/vaso-sanitario-convencional" },
            { title: "Vaso sanitário com caixa acoplada", href: "/categorias/loucas-sanitarias/vaso-sanitario-com-caixa-acoplada" },
            { title: "Caixa acoplada", href: "/categorias/loucas-sanitarias/caixa-acoplada" },
            { title: "Assento sanitário", href: "/categorias/loucas-sanitarias/assento-sanitario" },
            { title: "Lavatório de coluna", href: "/categorias/loucas-sanitarias/lavatorio-de-coluna" },
            { title: "Cuba de apoio", href: "/categorias/loucas-sanitarias/cuba-de-apoio" },
            { title: "Cuba de embutir", href: "/categorias/loucas-sanitarias/cuba-de-embutir" },
            { title: "Cuba de semi-encaixe", href: "/categorias/loucas-sanitarias/cuba-de-semi-encaixe" },
            { title: "Tanque de louça", href: "/categorias/loucas-sanitarias/tanque-de-louca" },
            { title: "Bidê", href: "/categorias/loucas-sanitarias/bide" },
            { title: "Mictório", href: "/categorias/loucas-sanitarias/mictorio" },
            { title: "Sifão para lavatório", href: "/categorias/loucas-sanitarias/sifao-para-lavatorio" },
            { title: "Kit de fixação sanitária", href: "/categorias/loucas-sanitarias/kit-de-fixacao-sanitaria" },
            { title: "Válvula de descarga", href: "/categorias/loucas-sanitarias/valvula-de-descarga" },
            { title: "Caixa de descarga", href: "/categorias/loucas-sanitarias/caixa-de-descarga" },
            { title: "Acabamento para válvula", href: "/categorias/loucas-sanitarias/acabamento-para-valvula" },
            { title: "Coluna para lavatório", href: "/categorias/loucas-sanitarias/coluna-para-lavatorio" },
            { title: "Saboneteira de louça", href: "/categorias/loucas-sanitarias/saboneteira-de-louca" },
            { title: "Porta-escova", href: "/categorias/loucas-sanitarias/porta-escova" },
            { title: "Cabide de louça", href: "/categorias/loucas-sanitarias/cabide-de-louca" },
            { title: "Papeleira de louça", href: "/categorias/loucas-sanitarias/papeleira-de-louca" },
            { title: "Lavatório suspenso", href: "/categorias/loucas-sanitarias/lavatorio-suspenso" },
            { title: "Cuba oval", href: "/categorias/loucas-sanitarias/cuba-oval" },
            { title: "Cuba retangular", href: "/categorias/loucas-sanitarias/cuba-retangular" },
            { title: "Lavatório pequeno", href: "/categorias/loucas-sanitarias/lavatorio-pequeno" },
            { title: "Lavatório grande", href: "/categorias/loucas-sanitarias/lavatorio-grande" },
            { title: "Tanque duplo", href: "/categorias/loucas-sanitarias/tanque-duplo" },
            { title: "Torneira para lavatório", href: "/categorias/loucas-sanitarias/torneira-para-lavatorio" },
            { title: "Torneira para tanque", href: "/categorias/loucas-sanitarias/torneira-para-tanque" },
            { title: "Acessórios de instalação", href: "/categorias/loucas-sanitarias/acessorios-de-instalacao" },
        ],
    },
    {
        title: "Metais Sanitários",
        subcategories: [
            { title: "Torneira de cozinha", href: "/categorias/metais-sanitarios/torneira-de-cozinha" },
            { title: "Torneira gourmet", href: "/categorias/metais-sanitarios/torneira-gourmet" },
            { title: "Torneira de banheiro", href: "/categorias/metais-sanitarios/torneira-de-banheiro" },
            { title: "Misturador monocomando", href: "/categorias/metais-sanitarios/misturador-monocomando" },
            { title: "Misturador duplo comando", href: "/categorias/metais-sanitarios/misturador-duplo-comando" },
            { title: "Registro de pressão", href: "/categorias/metais-sanitarios/registro-de-pressao" },
            { title: "Registro de gaveta", href: "/categorias/metais-sanitarios/registro-de-gaveta" },
            { title: "Acabamento de registro", href: "/categorias/metais-sanitarios/acabamento-de-registro" },
            { title: "Chuveiro", href: "/categorias/metais-sanitarios/chuveiro" },
            { title: "Ducha", href: "/categorias/metais-sanitarios/ducha" },
            { title: "Ducha higiênica", href: "/categorias/metais-sanitarios/ducha-higienica" },
            { title: "Válvula para pia", href: "/categorias/metais-sanitarios/valvula-para-pia" },
            { title: "Válvula para lavatório", href: "/categorias/metais-sanitarios/valvula-para-lavatorio" },
            { title: "Sifão metálico", href: "/categorias/metais-sanitarios/sifao-metalico" },
            { title: "Flexível inox", href: "/categorias/metais-sanitarios/flexivel-inox" },
            { title: "Porta-toalha", href: "/categorias/metais-sanitarios/porta-toalha" },
            { title: "Papeleira", href: "/categorias/metais-sanitarios/papeleira" },
            { title: "Saboneteira", href: "/categorias/metais-sanitarios/saboneteira" },
            { title: "Cabide", href: "/categorias/metais-sanitarios/cabide" },
            { title: "Barra de apoio", href: "/categorias/metais-sanitarios/barra-de-apoio" },
            { title: "Torneira de jardim", href: "/categorias/metais-sanitarios/torneira-de-jardim" },
            { title: "Torneira para tanque", href: "/categorias/metais-sanitarios/torneira-para-tanque" },
            { title: "Torneira automática", href: "/categorias/metais-sanitarios/torneira-automatica" },
            { title: "Acionador de descarga", href: "/categorias/metais-sanitarios/acionador-de-descarga" },
            { title: "Misturador para cozinha", href: "/categorias/metais-sanitarios/misturador-para-cozinha" },
            { title: "Acabamento cromado", href: "/categorias/metais-sanitarios/acabamento-cromado" },
            { title: "Acabamento preto fosco", href: "/categorias/metais-sanitarios/acabamento-preto-fosco" },
            { title: "Acabamento dourado", href: "/categorias/metais-sanitarios/acabamento-dourado" },
            { title: "Kit de acessórios banheiro", href: "/categorias/metais-sanitarios/kit-de-acessorios-banheiro" },
            { title: "Engate metálico", href: "/categorias/metais-sanitarios/engate-metalico" },
        ],
    },
    {
        title: "Pisos Cerâmicos",
        subcategories: [
            { title: "Piso cerâmico interno", href: "/categorias/pisos-ceramicos/piso-ceramico-interno" },
            { title: "Piso cerâmico externo", href: "/categorias/pisos-ceramicos/piso-ceramico-externo" },
            { title: "Piso acetinado", href: "/categorias/pisos-ceramicos/piso-acetinado" },
            { title: "Piso brilhante", href: "/categorias/pisos-ceramicos/piso-brilhante" },
            { title: "Piso antiderrapante", href: "/categorias/pisos-ceramicos/piso-antiderrapante" },
            { title: "Piso esmaltado", href: "/categorias/pisos-ceramicos/piso-esmaltado" },
            { title: "Piso rústico", href: "/categorias/pisos-ceramicos/piso-rustico" },
            { title: "Piso imitando madeira", href: "/categorias/pisos-ceramicos/piso-imitando-madeira" },
            { title: "Piso imitando cimento", href: "/categorias/pisos-ceramicos/piso-imitando-cimento" },
            { title: "Piso de alto tráfego", href: "/categorias/pisos-ceramicos/piso-de-alto-trafego" },
            { title: "Piso para garagem", href: "/categorias/pisos-ceramicos/piso-para-garagem" },
            { title: "Piso para varanda", href: "/categorias/pisos-ceramicos/piso-para-varanda" },
            { title: "Piso para banheiro", href: "/categorias/pisos-ceramicos/piso-para-banheiro" },
            { title: "Piso para cozinha", href: "/categorias/pisos-ceramicos/piso-para-cozinha" },
            { title: "Piso para área externa", href: "/categorias/pisos-ceramicos/piso-para-area-externa" },
            { title: "Rodapé cerâmico", href: "/categorias/pisos-ceramicos/rodape-ceramico" },
            { title: "Piso retificado", href: "/categorias/pisos-ceramicos/piso-retificado" },
            { title: "Piso bold", href: "/categorias/pisos-ceramicos/piso-bold" },
            { title: "Piso comercial", href: "/categorias/pisos-ceramicos/piso-comercial" },
            { title: "Piso residencial", href: "/categorias/pisos-ceramicos/piso-residencial" },
            { title: "Piso bege", href: "/categorias/pisos-ceramicos/piso-bege" },
            { title: "Piso cinza", href: "/categorias/pisos-ceramicos/piso-cinza" },
            { title: "Piso branco", href: "/categorias/pisos-ceramicos/piso-branco" },
            { title: "Piso preto", href: "/categorias/pisos-ceramicos/piso-preto" },
            { title: "Piso marrom", href: "/categorias/pisos-ceramicos/piso-marrom" },
            { title: "Piso texturizado", href: "/categorias/pisos-ceramicos/piso-texturizado" },
            { title: "Piso para escada", href: "/categorias/pisos-ceramicos/piso-para-escada" },
            { title: "Piso decorativo", href: "/categorias/pisos-ceramicos/piso-decorativo" },
            { title: "Piso quadrado", href: "/categorias/pisos-ceramicos/piso-quadrado" },
            { title: "Piso retangular", href: "/categorias/pisos-ceramicos/piso-retangular" },
        ],
    },
    {
        title: "Porcelanatos",
        subcategories: [
            { title: "Porcelanato polido", href: "/categorias/porcelanatos/porcelanato-polido" },
            { title: "Porcelanato acetinado", href: "/categorias/porcelanatos/porcelanato-acetinado" },
            { title: "Porcelanato externo", href: "/categorias/porcelanatos/porcelanato-externo" },
            { title: "Porcelanato interno", href: "/categorias/porcelanatos/porcelanato-interno" },
            { title: "Porcelanato grande formato", href: "/categorias/porcelanatos/porcelanato-grande-formato" },
            { title: "Porcelanato retificado", href: "/categorias/porcelanatos/porcelanato-retificado" },
            { title: "Porcelanato amadeirado", href: "/categorias/porcelanatos/porcelanato-amadeirado" },
            { title: "Porcelanato marmorizado", href: "/categorias/porcelanatos/porcelanato-marmorizado" },
            { title: "Porcelanato cimento queimado", href: "/categorias/porcelanatos/porcelanato-cimento-queimado" },
            { title: "Porcelanato bege", href: "/categorias/porcelanatos/porcelanato-bege" },
            { title: "Porcelanato cinza", href: "/categorias/porcelanatos/porcelanato-cinza" },
            { title: "Porcelanato branco", href: "/categorias/porcelanatos/porcelanato-branco" },
            { title: "Porcelanato preto", href: "/categorias/porcelanatos/porcelanato-preto" },
            { title: "Porcelanato para sala", href: "/categorias/porcelanatos/porcelanato-para-sala" },
            { title: "Porcelanato para cozinha", href: "/categorias/porcelanatos/porcelanato-para-cozinha" },
            { title: "Porcelanato para banheiro", href: "/categorias/porcelanatos/porcelanato-para-banheiro" },
            { title: "Porcelanato para varanda", href: "/categorias/porcelanatos/porcelanato-para-varanda" },
            { title: "Porcelanato para fachada", href: "/categorias/porcelanatos/porcelanato-para-fachada" },
            { title: "Porcelanato antiderrapante", href: "/categorias/porcelanatos/porcelanato-antiderrapante" },
            { title: "Porcelanato técnico", href: "/categorias/porcelanatos/porcelanato-tecnico" },
            { title: "Porcelanato esmaltado", href: "/categorias/porcelanatos/porcelanato-esmaltado" },
            { title: "Borda para porcelanato", href: "/categorias/porcelanatos/borda-para-porcelanato" },
            { title: "Rodapé porcelanato", href: "/categorias/porcelanatos/rodape-porcelanato" },
            { title: "Porcelanato 60x60", href: "/categorias/porcelanatos/porcelanato-60x60" },
            { title: "Porcelanato 80x80", href: "/categorias/porcelanatos/porcelanato-80x80" },
            { title: "Porcelanato 90x90", href: "/categorias/porcelanatos/porcelanato-90x90" },
            { title: "Porcelanato 120x120", href: "/categorias/porcelanatos/porcelanato-120x120" },
            { title: "Porcelanato slim", href: "/categorias/porcelanatos/porcelanato-slim" },
            { title: "Porcelanato decorado", href: "/categorias/porcelanatos/porcelanato-decorado" },
            { title: "Porcelanato comercial", href: "/categorias/porcelanatos/porcelanato-comercial" },
        ],
    },
    {
        title: "Revestimentos de Parede",
        subcategories: [
            { title: "Revestimento cerâmico", href: "/categorias/revestimentos-de-parede/revestimento-ceramico" },
            { title: "Revestimento retificado", href: "/categorias/revestimentos-de-parede/revestimento-retificado" },
            { title: "Revestimento brilhante", href: "/categorias/revestimentos-de-parede/revestimento-brilhante" },
            { title: "Revestimento acetinado", href: "/categorias/revestimentos-de-parede/revestimento-acetinado" },
            { title: "Revestimento 3D", href: "/categorias/revestimentos-de-parede/revestimento-3d" },
            { title: "Pastilha de vidro", href: "/categorias/revestimentos-de-parede/pastilha-de-vidro" },
            { title: "Pastilha cerâmica", href: "/categorias/revestimentos-de-parede/pastilha-ceramica" },
            { title: "Pastilha metálica", href: "/categorias/revestimentos-de-parede/pastilha-metalica" },
            { title: "Revestimento para cozinha", href: "/categorias/revestimentos-de-parede/revestimento-para-cozinha" },
            { title: "Revestimento para banheiro", href: "/categorias/revestimentos-de-parede/revestimento-para-banheiro" },
            { title: "Revestimento para lavanderia", href: "/categorias/revestimentos-de-parede/revestimento-para-lavanderia" },
            { title: "Revestimento para fachada", href: "/categorias/revestimentos-de-parede/revestimento-para-fachada" },
            { title: "Revestimento decorativo", href: "/categorias/revestimentos-de-parede/revestimento-decorativo" },
            { title: "Filete decorativo", href: "/categorias/revestimentos-de-parede/filete-decorativo" },
            { title: "Rodameio", href: "/categorias/revestimentos-de-parede/rodameio" },
            { title: "Faixa decorativa", href: "/categorias/revestimentos-de-parede/faixa-decorativa" },
            { title: "Tijolinho decorativo", href: "/categorias/revestimentos-de-parede/tijolinho-decorativo" },
            { title: "Pedra decorativa", href: "/categorias/revestimentos-de-parede/pedra-decorativa" },
            { title: "Revestimento cimentício", href: "/categorias/revestimentos-de-parede/revestimento-cimenticio" },
            { title: "Revestimento de gesso", href: "/categorias/revestimentos-de-parede/revestimento-de-gesso" },
            { title: "Placa decorativa", href: "/categorias/revestimentos-de-parede/placa-decorativa" },
            { title: "Painel ripado", href: "/categorias/revestimentos-de-parede/painel-ripado" },
            { title: "Revestimento marmorizado", href: "/categorias/revestimentos-de-parede/revestimento-marmorizado" },
            { title: "Revestimento amadeirado", href: "/categorias/revestimentos-de-parede/revestimento-amadeirado" },
            { title: "Revestimento hexagonal", href: "/categorias/revestimentos-de-parede/revestimento-hexagonal" },
            { title: "Revestimento subway", href: "/categorias/revestimentos-de-parede/revestimento-subway" },
            { title: "Revestimento alto brilho", href: "/categorias/revestimentos-de-parede/revestimento-alto-brilho" },
            { title: "Revestimento fosco", href: "/categorias/revestimentos-de-parede/revestimento-fosco" },
            { title: "Revestimento externo", href: "/categorias/revestimentos-de-parede/revestimento-externo" },
            { title: "Revestimento interno", href: "/categorias/revestimentos-de-parede/revestimento-interno" },
        ],
    },
    {
        title: "Tintas",
        subcategories: [
            { title: "Tinta acrílica fosca", href: "/categorias/tintas/tinta-acrilica-fosca" },
            { title: "Tinta acrílica semibrilho", href: "/categorias/tintas/tinta-acrilica-semibrilho" },
            { title: "Tinta acrílica brilhante", href: "/categorias/tintas/tinta-acrilica-brilhante" },
            { title: "Tinta PVA", href: "/categorias/tintas/tinta-pva" },
            { title: "Tinta esmalte sintético", href: "/categorias/tintas/tinta-esmalte-sintetico" },
            { title: "Tinta epóxi", href: "/categorias/tintas/tinta-epoxi" },
            { title: "Tinta emborrachada", href: "/categorias/tintas/tinta-emborrachada" },
            { title: "Tinta para piso", href: "/categorias/tintas/tinta-para-piso" },
            { title: "Tinta para telha", href: "/categorias/tintas/tinta-para-telha" },
            { title: "Tinta para madeira", href: "/categorias/tintas/tinta-para-madeira" },
            { title: "Tinta para metal", href: "/categorias/tintas/tinta-para-metal" },
            { title: "Tinta spray", href: "/categorias/tintas/tinta-spray" },
            { title: "Tinta impermeabilizante", href: "/categorias/tintas/tinta-impermeabilizante" },
            { title: "Fundo preparador", href: "/categorias/tintas/fundo-preparador" },
            { title: "Selador acrílico", href: "/categorias/tintas/selador-acrilico" },
            { title: "Massa corrida", href: "/categorias/tintas/massa-corrida" },
            { title: "Massa acrílica", href: "/categorias/tintas/massa-acrilica" },
            { title: "Verniz", href: "/categorias/tintas/verniz" },
            { title: "Stain", href: "/categorias/tintas/stain" },
            { title: "Solvente", href: "/categorias/tintas/solvente" },
            { title: "Aguarrás", href: "/categorias/tintas/aguarras" },
            { title: "Thinner", href: "/categorias/tintas/thinner" },
            { title: "Corante líquido", href: "/categorias/tintas/corante-liquido" },
            { title: "Textura", href: "/categorias/tintas/textura" },
            { title: "Grafiato", href: "/categorias/tintas/grafiato" },
            { title: "Complemento para pintura", href: "/categorias/tintas/complemento-para-pintura" },
            { title: "Tinta para fachada", href: "/categorias/tintas/tinta-para-fachada" },
            { title: "Tinta para banheiro", href: "/categorias/tintas/tinta-para-banheiro" },
            { title: "Tinta para azulejo", href: "/categorias/tintas/tinta-para-azulejo" },
            { title: "Removedor de tinta", href: "/categorias/tintas/removedor-de-tinta" },
        ],
    },
    {
        title: "Ferramentas Manuais",
        subcategories: [
            { title: "Martelo", href: "/categorias/ferramentas-manuais/martelo" },
            { title: "Marreta", href: "/categorias/ferramentas-manuais/marreta" },
            { title: "Chave de fenda", href: "/categorias/ferramentas-manuais/chave-de-fenda" },
            { title: "Chave philips", href: "/categorias/ferramentas-manuais/chave-philips" },
            { title: "Chave combinada", href: "/categorias/ferramentas-manuais/chave-combinada" },
            { title: "Alicate universal", href: "/categorias/ferramentas-manuais/alicate-universal" },
            { title: "Alicate de corte", href: "/categorias/ferramentas-manuais/alicate-de-corte" },
            { title: "Alicate de pressão", href: "/categorias/ferramentas-manuais/alicate-de-pressao" },
            { title: "Trena", href: "/categorias/ferramentas-manuais/trena" },
            { title: "Nível manual", href: "/categorias/ferramentas-manuais/nivel-manual" },
            { title: "Esquadro", href: "/categorias/ferramentas-manuais/esquadro" },
            { title: "Serrote", href: "/categorias/ferramentas-manuais/serrote" },
            { title: "Arco de serra", href: "/categorias/ferramentas-manuais/arco-de-serra" },
            { title: "Estilete", href: "/categorias/ferramentas-manuais/estilete" },
            { title: "Pá", href: "/categorias/ferramentas-manuais/pa" },
            { title: "Enxada", href: "/categorias/ferramentas-manuais/enxada" },
            { title: "Colher de pedreiro", href: "/categorias/ferramentas-manuais/colher-de-pedreiro" },
            { title: "Desempenadeira", href: "/categorias/ferramentas-manuais/desempenadeira" },
            { title: "Espátula", href: "/categorias/ferramentas-manuais/espatula" },
            { title: "Talhadeira", href: "/categorias/ferramentas-manuais/talhadeira" },
            { title: "Ponteiro", href: "/categorias/ferramentas-manuais/ponteiro" },
            { title: "Saca-prego", href: "/categorias/ferramentas-manuais/saca-prego" },
            { title: "Torquês", href: "/categorias/ferramentas-manuais/torques" },
            { title: "Grampos", href: "/categorias/ferramentas-manuais/grampos" },
            { title: "Chave inglesa", href: "/categorias/ferramentas-manuais/chave-inglesa" },
            { title: "Grifo", href: "/categorias/ferramentas-manuais/grifo" },
            { title: "Tesoura para chapa", href: "/categorias/ferramentas-manuais/tesoura-para-chapa" },
            { title: "Plaina manual", href: "/categorias/ferramentas-manuais/plaina-manual" },
            { title: "Formão", href: "/categorias/ferramentas-manuais/formao" },
            { title: "Carrinho de mão", href: "/categorias/ferramentas-manuais/carrinho-de-mao" },
        ],
    },
    {
        title: "Ferramentas Elétricas",
        subcategories: [
            { title: "Furadeira", href: "/categorias/ferramentas-eletricas/furadeira" },
            { title: "Parafusadeira", href: "/categorias/ferramentas-eletricas/parafusadeira" },
            { title: "Martelete", href: "/categorias/ferramentas-eletricas/martelete" },
            { title: "Esmerilhadeira", href: "/categorias/ferramentas-eletricas/esmerilhadeira" },
            { title: "Serra mármore", href: "/categorias/ferramentas-eletricas/serra-marmore" },
            { title: "Serra circular", href: "/categorias/ferramentas-eletricas/serra-circular" },
            { title: "Serra tico-tico", href: "/categorias/ferramentas-eletricas/serra-tico-tico" },
            { title: "Serra sabre", href: "/categorias/ferramentas-eletricas/serra-sabre" },
            { title: "Lixadeira orbital", href: "/categorias/ferramentas-eletricas/lixadeira-orbital" },
            { title: "Lixadeira roto orbital", href: "/categorias/ferramentas-eletricas/lixadeira-roto-orbital" },
            { title: "Plaina elétrica", href: "/categorias/ferramentas-eletricas/plaina-eletrica" },
            { title: "Tupia", href: "/categorias/ferramentas-eletricas/tupia" },
            { title: "Politriz", href: "/categorias/ferramentas-eletricas/politriz" },
            { title: "Soprador térmico", href: "/categorias/ferramentas-eletricas/soprador-termico" },
            { title: "Pistola de pintura", href: "/categorias/ferramentas-eletricas/pistola-de-pintura" },
            { title: "Compressor", href: "/categorias/ferramentas-eletricas/compressor" },
            { title: "Gerador", href: "/categorias/ferramentas-eletricas/gerador" },
            { title: "Bomba d’água", href: "/categorias/ferramentas-eletricas/bomba-dagua" },
            { title: "Cortador de piso", href: "/categorias/ferramentas-eletricas/cortador-de-piso" },
            { title: "Misturador elétrico", href: "/categorias/ferramentas-eletricas/misturador-eletrico" },
            { title: "Perfurador de solo", href: "/categorias/ferramentas-eletricas/perfurador-de-solo" },
            { title: "Aspirador de pó", href: "/categorias/ferramentas-eletricas/aspirador-de-po" },
            { title: "Lavadora de alta pressão", href: "/categorias/ferramentas-eletricas/lavadora-de-alta-pressao" },
            { title: "Roçadeira", href: "/categorias/ferramentas-eletricas/rocadeira" },
            { title: "Motosserra", href: "/categorias/ferramentas-eletricas/motosserra" },
            { title: "Aparador de grama", href: "/categorias/ferramentas-eletricas/aparador-de-grama" },
            { title: "Carregador de bateria", href: "/categorias/ferramentas-eletricas/carregador-de-bateria" },
            { title: "Bateria para ferramenta", href: "/categorias/ferramentas-eletricas/bateria-para-ferramenta" },
            { title: "Maleta de ferramenta", href: "/categorias/ferramentas-eletricas/maleta-de-ferramenta" },
            { title: "Acessórios para ferramentas elétricas", href: "/categorias/ferramentas-eletricas/acessorios-para-ferramentas-eletricas" },
        ],
    },
    {
        title: "Fixação e Parafusos",
        subcategories: [
            { title: "Parafuso para madeira", href: "/categorias/fixacao-e-parafusos/parafuso-para-madeira" },
            { title: "Parafuso para metal", href: "/categorias/fixacao-e-parafusos/parafuso-para-metal" },
            { title: "Parafuso para drywall", href: "/categorias/fixacao-e-parafusos/parafuso-para-drywall" },
            { title: "Parafuso autobrocante", href: "/categorias/fixacao-e-parafusos/parafuso-autobrocante" },
            { title: "Parafuso sextavado", href: "/categorias/fixacao-e-parafusos/parafuso-sextavado" },
            { title: "Parafuso chipboard", href: "/categorias/fixacao-e-parafusos/parafuso-chipboard" },
            { title: "Bucha nylon", href: "/categorias/fixacao-e-parafusos/bucha-nylon" },
            { title: "Bucha de impacto", href: "/categorias/fixacao-e-parafusos/bucha-de-impacto" },
            { title: "Bucha metálica", href: "/categorias/fixacao-e-parafusos/bucha-metalica" },
            { title: "Bucha para drywall", href: "/categorias/fixacao-e-parafusos/bucha-para-drywall" },
            { title: "Prego com cabeça", href: "/categorias/fixacao-e-parafusos/prego-com-cabeca" },
            { title: "Prego sem cabeça", href: "/categorias/fixacao-e-parafusos/prego-sem-cabeca" },
            { title: "Prego para telha", href: "/categorias/fixacao-e-parafusos/prego-para-telha" },
            { title: "Rebite", href: "/categorias/fixacao-e-parafusos/rebite" },
            { title: "Porca sextavada", href: "/categorias/fixacao-e-parafusos/porca-sextavada" },
            { title: "Arruela lisa", href: "/categorias/fixacao-e-parafusos/arruela-lisa" },
            { title: "Arruela de pressão", href: "/categorias/fixacao-e-parafusos/arruela-de-pressao" },
            { title: "Barra roscada", href: "/categorias/fixacao-e-parafusos/barra-roscada" },
            { title: "Gancho", href: "/categorias/fixacao-e-parafusos/gancho" },
            { title: "Chumbador", href: "/categorias/fixacao-e-parafusos/chumbador" },
            { title: "Chumbador químico", href: "/categorias/fixacao-e-parafusos/chumbador-quimico" },
            { title: "Anel de fixação", href: "/categorias/fixacao-e-parafusos/anel-de-fixacao" },
            { title: "Abraçadeira", href: "/categorias/fixacao-e-parafusos/abracadeira" },
            { title: "Corrente", href: "/categorias/fixacao-e-parafusos/corrente" },
            { title: "Fecho", href: "/categorias/fixacao-e-parafusos/fecho" },
            { title: "Dobradiça", href: "/categorias/fixacao-e-parafusos/dobradica" },
            { title: "Suporte de prateleira", href: "/categorias/fixacao-e-parafusos/suporte-de-prateleira" },
            { title: "Cantoneira de fixação", href: "/categorias/fixacao-e-parafusos/cantoneira-de-fixacao" },
            { title: "Fixador de telha", href: "/categorias/fixacao-e-parafusos/fixador-de-telha" },
            { title: "Kit de fixação", href: "/categorias/fixacao-e-parafusos/kit-de-fixacao" },
        ],
    },
    {
        title: "Portas e Janelas",
        subcategories: [
            { title: "Porta de madeira", href: "/categorias/portas-e-janelas/porta-de-madeira" },
            { title: "Porta de alumínio", href: "/categorias/portas-e-janelas/porta-de-aluminio" },
            { title: "Porta de aço", href: "/categorias/portas-e-janelas/porta-de-aco" },
            { title: "Porta sanfonada", href: "/categorias/portas-e-janelas/porta-sanfonada" },
            { title: "Porta balcão", href: "/categorias/portas-e-janelas/porta-balcao" },
            { title: "Janela de alumínio", href: "/categorias/portas-e-janelas/janela-de-aluminio" },
            { title: "Janela de aço", href: "/categorias/portas-e-janelas/janela-de-aco" },
            { title: "Janela maxim-ar", href: "/categorias/portas-e-janelas/janela-maxim-ar" },
            { title: "Janela de correr", href: "/categorias/portas-e-janelas/janela-de-correr" },
            { title: "Janela basculante", href: "/categorias/portas-e-janelas/janela-basculante" },
            { title: "Vitro", href: "/categorias/portas-e-janelas/vitro" },
            { title: "Batente", href: "/categorias/portas-e-janelas/batente" },
            { title: "Guarnição", href: "/categorias/portas-e-janelas/guarnicao" },
            { title: "Fechadura", href: "/categorias/portas-e-janelas/fechadura" },
            { title: "Maçaneta", href: "/categorias/portas-e-janelas/macaneta" },
            { title: "Dobradiça", href: "/categorias/portas-e-janelas/dobradica" },
            { title: "Trilho para porta", href: "/categorias/portas-e-janelas/trilho-para-porta" },
            { title: "Roldana", href: "/categorias/portas-e-janelas/roldana" },
            { title: "Veneziana", href: "/categorias/portas-e-janelas/veneziana" },
            { title: "Porta pivotante", href: "/categorias/portas-e-janelas/porta-pivotante" },
            { title: "Janela com grade", href: "/categorias/portas-e-janelas/janela-com-grade" },
            { title: "Porta interna", href: "/categorias/portas-e-janelas/porta-interna" },
            { title: "Porta externa", href: "/categorias/portas-e-janelas/porta-externa" },
            { title: "Porta para banheiro", href: "/categorias/portas-e-janelas/porta-para-banheiro" },
            { title: "Porta para quarto", href: "/categorias/portas-e-janelas/porta-para-quarto" },
            { title: "Janela para cozinha", href: "/categorias/portas-e-janelas/janela-para-cozinha" },
            { title: "Janela para banheiro", href: "/categorias/portas-e-janelas/janela-para-banheiro" },
            { title: "Soleira", href: "/categorias/portas-e-janelas/soleira" },
            { title: "Peitoril", href: "/categorias/portas-e-janelas/peitoril" },
            { title: "Kit porta pronta", href: "/categorias/portas-e-janelas/kit-porta-pronta" },
        ],
    },
    {
        title: "Drywall e Gesso",
        subcategories: [
            { title: "Chapa drywall ST", href: "/categorias/drywall-e-gesso/chapa-drywall-st" },
            { title: "Chapa drywall RU", href: "/categorias/drywall-e-gesso/chapa-drywall-ru" },
            { title: "Chapa drywall RF", href: "/categorias/drywall-e-gesso/chapa-drywall-rf" },
            { title: "Perfil montante", href: "/categorias/drywall-e-gesso/perfil-montante" },
            { title: "Perfil guia", href: "/categorias/drywall-e-gesso/perfil-guia" },
            { title: "Cantoneira para drywall", href: "/categorias/drywall-e-gesso/cantoneira-para-drywall" },
            { title: "Massa para drywall", href: "/categorias/drywall-e-gesso/massa-para-drywall" },
            { title: "Fita para junta", href: "/categorias/drywall-e-gesso/fita-para-junta" },
            { title: "Parafuso drywall", href: "/categorias/drywall-e-gesso/parafuso-drywall" },
            { title: "Bucha para drywall", href: "/categorias/drywall-e-gesso/bucha-para-drywall" },
            { title: "Lã de vidro", href: "/categorias/drywall-e-gesso/la-de-vidro" },
            { title: "Lã de rocha", href: "/categorias/drywall-e-gesso/la-de-rocha" },
            { title: "Forro de gesso", href: "/categorias/drywall-e-gesso/forro-de-gesso" },
            { title: "Placa 3D de gesso", href: "/categorias/drywall-e-gesso/placa-3d-de-gesso" },
            { title: "Moldura de gesso", href: "/categorias/drywall-e-gesso/moldura-de-gesso" },
            { title: "Gesso em pó", href: "/categorias/drywall-e-gesso/gesso-em-po" },
            { title: "Gesso cola", href: "/categorias/drywall-e-gesso/gesso-cola" },
            { title: "Sanca", href: "/categorias/drywall-e-gesso/sanca" },
            { title: "Roda teto", href: "/categorias/drywall-e-gesso/roda-teto" },
            { title: "Divisória drywall", href: "/categorias/drywall-e-gesso/divisoria-drywall" },
            { title: "Porta para drywall", href: "/categorias/drywall-e-gesso/porta-para-drywall" },
            { title: "Alçapão de inspeção", href: "/categorias/drywall-e-gesso/alcapao-de-inspecao" },
            { title: "Suspensão para forro", href: "/categorias/drywall-e-gesso/suspensao-para-forro" },
            { title: "Perfil tabica", href: "/categorias/drywall-e-gesso/perfil-tabica" },
            { title: "Massa para acabamento", href: "/categorias/drywall-e-gesso/massa-para-acabamento" },
            { title: "Tela para junta", href: "/categorias/drywall-e-gesso/tela-para-junta" },
            { title: "Reparo em gesso", href: "/categorias/drywall-e-gesso/reparo-em-gesso" },
            { title: "Painel de gesso", href: "/categorias/drywall-e-gesso/painel-de-gesso" },
            { title: "Forro removível", href: "/categorias/drywall-e-gesso/forro-removivel" },
            { title: "Acessórios para drywall", href: "/categorias/drywall-e-gesso/acessorios-para-drywall" },
        ],
    },
    {
        title: "Forros e Divisórias",
        subcategories: [
            { title: "Forro PVC", href: "/categorias/forros-e-divisorias/forro-pvc" },
            { title: "Forro de gesso", href: "/categorias/forros-e-divisorias/forro-de-gesso" },
            { title: "Forro mineral", href: "/categorias/forros-e-divisorias/forro-mineral" },
            { title: "Forro de madeira", href: "/categorias/forros-e-divisorias/forro-de-madeira" },
            { title: "Forro modular", href: "/categorias/forros-e-divisorias/forro-modular" },
            { title: "Forro removível", href: "/categorias/forros-e-divisorias/forro-removivel" },
            { title: "Divisória naval", href: "/categorias/forros-e-divisorias/divisoria-naval" },
            { title: "Divisória drywall", href: "/categorias/forros-e-divisorias/divisoria-drywall" },
            { title: "Divisória Eucatex", href: "/categorias/forros-e-divisorias/divisoria-eucatex" },
            { title: "Painel divisório", href: "/categorias/forros-e-divisorias/painel-divisorio" },
            { title: "Perfil para forro", href: "/categorias/forros-e-divisorias/perfil-para-forro" },
            { title: "Emenda para forro", href: "/categorias/forros-e-divisorias/emenda-para-forro" },
            { title: "Rodaforro", href: "/categorias/forros-e-divisorias/rodaforro" },
            { title: "Cantoneira para forro", href: "/categorias/forros-e-divisorias/cantoneira-para-forro" },
            { title: "Arremate para forro", href: "/categorias/forros-e-divisorias/arremate-para-forro" },
            { title: "Suporte para forro", href: "/categorias/forros-e-divisorias/suporte-para-forro" },
            { title: "Pendural", href: "/categorias/forros-e-divisorias/pendural" },
            { title: "Estrutura metálica para forro", href: "/categorias/forros-e-divisorias/estrutura-metalica-para-forro" },
            { title: "Placa acústica", href: "/categorias/forros-e-divisorias/placa-acustica" },
            { title: "Placa térmica", href: "/categorias/forros-e-divisorias/placa-termica" },
            { title: "Painel ripado", href: "/categorias/forros-e-divisorias/painel-ripado" },
            { title: "Divisória de ambiente", href: "/categorias/forros-e-divisorias/divisoria-de-ambiente" },
            { title: "Forro decorativo", href: "/categorias/forros-e-divisorias/forro-decorativo" },
            { title: "Forro branco", href: "/categorias/forros-e-divisorias/forro-branco" },
            { title: "Forro amadeirado", href: "/categorias/forros-e-divisorias/forro-amadeirado" },
            { title: "Porta para divisória", href: "/categorias/forros-e-divisorias/porta-para-divisoria" },
            { title: "Janela para divisória", href: "/categorias/forros-e-divisorias/janela-para-divisoria" },
            { title: "Acessórios de montagem", href: "/categorias/forros-e-divisorias/acessorios-de-montagem" },
            { title: "Perfil T", href: "/categorias/forros-e-divisorias/perfil-t" },
            { title: "Perfil clicado", href: "/categorias/forros-e-divisorias/perfil-clicado" },
        ],
    },
    {
        title: "Esquadrias e Acessórios",
        subcategories: [
            { title: "Fechadura externa", href: "/categorias/esquadrias-e-acessorios/fechadura-externa" },
            { title: "Fechadura interna", href: "/categorias/esquadrias-e-acessorios/fechadura-interna" },
            { title: "Fechadura para banheiro", href: "/categorias/esquadrias-e-acessorios/fechadura-para-banheiro" },
            { title: "Maçaneta", href: "/categorias/esquadrias-e-acessorios/macaneta" },
            { title: "Puxador", href: "/categorias/esquadrias-e-acessorios/puxador" },
            { title: "Dobradiça", href: "/categorias/esquadrias-e-acessorios/dobradica" },
            { title: "Mola aérea", href: "/categorias/esquadrias-e-acessorios/mola-aerea" },
            { title: "Olho mágico", href: "/categorias/esquadrias-e-acessorios/olho-magico" },
            { title: "Trinco", href: "/categorias/esquadrias-e-acessorios/trinco" },
            { title: "Cadeado", href: "/categorias/esquadrias-e-acessorios/cadeado" },
            { title: "Corrente de segurança", href: "/categorias/esquadrias-e-acessorios/corrente-de-seguranca" },
            { title: "Porta cadeado", href: "/categorias/esquadrias-e-acessorios/porta-cadeado" },
            { title: "Roldana", href: "/categorias/esquadrias-e-acessorios/roldana" },
            { title: "Trilho", href: "/categorias/esquadrias-e-acessorios/trilho" },
            { title: "Batente metálico", href: "/categorias/esquadrias-e-acessorios/batente-metalico" },
            { title: "Guarnição", href: "/categorias/esquadrias-e-acessorios/guarnicao" },
            { title: "Escova de vedação", href: "/categorias/esquadrias-e-acessorios/escova-de-vedacao" },
            { title: "Borracha de vedação", href: "/categorias/esquadrias-e-acessorios/borracha-de-vedacao" },
            { title: "Limitador de porta", href: "/categorias/esquadrias-e-acessorios/limitador-de-porta" },
            { title: "Soleira", href: "/categorias/esquadrias-e-acessorios/soleira" },
            { title: "Peitoril", href: "/categorias/esquadrias-e-acessorios/peitoril" },
            { title: "Grade de proteção", href: "/categorias/esquadrias-e-acessorios/grade-de-protecao" },
            { title: "Tela mosquiteira", href: "/categorias/esquadrias-e-acessorios/tela-mosquiteira" },
            { title: "Veneziana", href: "/categorias/esquadrias-e-acessorios/veneziana" },
            { title: "Braço para janela", href: "/categorias/esquadrias-e-acessorios/braco-para-janela" },
            { title: "Pistão para janela", href: "/categorias/esquadrias-e-acessorios/pistao-para-janela" },
            { title: "Suporte basculante", href: "/categorias/esquadrias-e-acessorios/suporte-basculante" },
            { title: "Fecho para janela", href: "/categorias/esquadrias-e-acessorios/fecho-para-janela" },
            { title: "Acessórios para correr", href: "/categorias/esquadrias-e-acessorios/acessorios-para-correr" },
            { title: "Kit instalação esquadria", href: "/categorias/esquadrias-e-acessorios/kit-instalacao-esquadria" },
        ],
    },
    {
        title: "Banheiro",
        subcategories: [
            { title: "Vaso sanitário", href: "/categorias/banheiro/vaso-sanitario" },
            { title: "Assento sanitário", href: "/categorias/banheiro/assento-sanitario" },
            { title: "Caixa acoplada", href: "/categorias/banheiro/caixa-acoplada" },
            { title: "Lavatório", href: "/categorias/banheiro/lavatorio" },
            { title: "Cuba", href: "/categorias/banheiro/cuba" },
            { title: "Torneira", href: "/categorias/banheiro/torneira" },
            { title: "Chuveiro", href: "/categorias/banheiro/chuveiro" },
            { title: "Ducha higiênica", href: "/categorias/banheiro/ducha-higienica" },
            { title: "Registro", href: "/categorias/banheiro/registro" },
            { title: "Sifão", href: "/categorias/banheiro/sifao" },
            { title: "Ralo", href: "/categorias/banheiro/ralo" },
            { title: "Box de banheiro", href: "/categorias/banheiro/box-de-banheiro" },
            { title: "Espelho", href: "/categorias/banheiro/espelho" },
            { title: "Armário de banheiro", href: "/categorias/banheiro/armario-de-banheiro" },
            { title: "Nicho", href: "/categorias/banheiro/nicho" },
            { title: "Porta-toalha", href: "/categorias/banheiro/porta-toalha" },
            { title: "Papeleira", href: "/categorias/banheiro/papeleira" },
            { title: "Saboneteira", href: "/categorias/banheiro/saboneteira" },
            { title: "Cabide", href: "/categorias/banheiro/cabide" },
            { title: "Barra de apoio", href: "/categorias/banheiro/barra-de-apoio" },
            { title: "Tapete antiderrapante", href: "/categorias/banheiro/tapete-antiderrapante" },
            { title: "Revestimento para banheiro", href: "/categorias/banheiro/revestimento-para-banheiro" },
            { title: "Piso para banheiro", href: "/categorias/banheiro/piso-para-banheiro" },
            { title: "Iluminação para banheiro", href: "/categorias/banheiro/iluminacao-for-banheiro" },
            { title: "Exaustor", href: "/categorias/banheiro/exaustor" },
            { title: "Acessórios cromados", href: "/categorias/banheiro/acessorios-cromados" },
            { title: "Acessórios pretos", href: "/categorias/banheiro/acessorios-pretos" },
            { title: "Kit banheiro completo", href: "/categorias/banheiro/kit-banheiro-completo" },
            { title: "Gabinete para pia", href: "/categorias/banheiro/gabinete-para-pia" },
            { title: "Válvula de descarga", href: "/categorias/banheiro/valvula-de-descarga" },
        ],
    },
    {
        title: "Cozinha e Área de Serviço",
        subcategories: [
            { title: "Pia de cozinha", href: "/categorias/cozinha-e-area-de-servico/pia-de-cozinha" },
            { title: "Cuba inox", href: "/categorias/cozinha-e-area-de-servico/cuba-inox" },
            { title: "Torneira de cozinha", href: "/categorias/cozinha-e-area-de-servico/torneira-de-cozinha" },
            { title: "Misturador gourmet", href: "/categorias/cozinha-e-area-de-servico/misturador-gourmet" },
            { title: "Sifão", href: "/categorias/cozinha-e-area-de-servico/sifao" },
            { title: "Válvula para pia", href: "/categorias/cozinha-e-area-de-servico/valvula-para-pia" },
            { title: "Tanque", href: "/categorias/cozinha-e-area-de-servico/tanque" },
            { title: "Torneira para tanque", href: "/categorias/cozinha-e-area-de-servico/torneira-para-tanque" },
            { title: "Engate flexível", href: "/categorias/cozinha-e-area-de-servico/engate-flexivel" },
            { title: "Armário aéreo", href: "/categorias/cozinha-e-area-de-servico/armario-aereo" },
            { title: "Balcão de cozinha", href: "/categorias/cozinha-e-area-de-servico/balcao-de-cozinha" },
            { title: "Gabinete de pia", href: "/categorias/cozinha-e-area-de-servico/gabinete-de-pia" },
            { title: "Bancada de granito", href: "/categorias/cozinha-e-area-de-servico/bancada-de-granito" },
            { title: "Bancada de mármore", href: "/categorias/cozinha-e-area-de-servico/bancada-de-marmore" },
            { title: "Cooktop", href: "/categorias/cozinha-e-area-de-servico/cooktop" },
            { title: "Depurador", href: "/categorias/cozinha-e-area-de-servico/depurador" },
            { title: "Coifa", href: "/categorias/cozinha-e-area-de-servico/coifa" },
            { title: "Revestimento para cozinha", href: "/categorias/cozinha-e-area-de-servico/revestimento-para-cozinha" },
            { title: "Piso para cozinha", href: "/categorias/cozinha-e-area-de-servico/piso-para-cozinha" },
            { title: "Rodabanca", href: "/categorias/cozinha-e-area-de-servico/rodabanca" },
            { title: "Prateleira", href: "/categorias/cozinha-e-area-de-servico/prateleira" },
            { title: "Suporte para micro-ondas", href: "/categorias/cozinha-e-area-de-servico/suporte-para-micro-ondas" },
            { title: "Varal de parede", href: "/categorias/cozinha-e-area-de-servico/varal-de-parede" },
            { title: "Varal de teto", href: "/categorias/cozinha-e-area-de-servico/varal-de-teto" },
            { title: "Porta detergente", href: "/categorias/cozinha-e-area-de-servico/porta-detergente" },
            { title: "Escorredor embutido", href: "/categorias/cozinha-e-area-de-servico/escorredor-embutido" },
            { title: "Lixeira embutida", href: "/categorias/cozinha-e-area-de-servico/lixeira-embutida" },
            { title: "Organizador de lavanderia", href: "/categorias/cozinha-e-area-de-servico/organizador-de-lavanderia" },
            { title: "Acessórios hidráulicos", href: "/categorias/cozinha-e-area-de-servico/acessorios-hidraulicos" },
            { title: "Acessórios elétricos", href: "/categorias/cozinha-e-area-de-servico/acessorios-eletricos" },
        ],
    },
    {
        title: "Jardinagem e Área Externa",
        subcategories: [
            { title: "Terra vegetal", href: "/categorias/jardinagem-e-area-externa/terra-vegetal" },
            { title: "Adubo", href: "/categorias/jardinagem-e-area-externa/adubo" },
            { title: "Vaso de planta", href: "/categorias/jardinagem-e-area-externa/vaso-de-planta" },
            { title: "Prato para vaso", href: "/categorias/jardinagem-e-area-externa/prato-para-vaso" },
            { title: "Pedra decorativa", href: "/categorias/jardinagem-e-area-externa/pedra-decorativa" },
            { title: "Grama sintética", href: "/categorias/jardinagem-e-area-externa/grama-sintetica" },
            { title: "Grama natural", href: "/categorias/jardinagem-e-area-externa/grama-natural" },
            { title: "Mangueira", href: "/categorias/jardinagem-e-area-externa/mangueira" },
            { title: "Esguicho", href: "/categorias/jardinagem-e-area-externa/esguicho" },
            { title: "Regador", href: "/categorias/jardinagem-e-area-externa/regador" },
            { title: "Pá de jardim", href: "/categorias/jardinagem-e-area-externa/pa-de-jardim" },
            { title: "Rastelo", href: "/categorias/jardinagem-e-area-externa/rastelo" },
            { title: "Tesoura de poda", href: "/categorias/jardinagem-e-area-externa/tesoura-de-poda" },
            { title: "Serrote de poda", href: "/categorias/jardinagem-e-area-externa/serrote-de-poda" },
            { title: "Pulverizador", href: "/categorias/jardinagem-e-area-externa/pulverizador" },
            { title: "Cerca para jardim", href: "/categorias/jardinagem-e-area-externa/cerca-para-jardim" },
            { title: "Piso drenante", href: "/categorias/jardinagem-e-area-externa/piso-drenante" },
            { title: "Deck modular", href: "/categorias/jardinagem-e-area-externa/deck-modular" },
            { title: "Refletor externo", href: "/categorias/jardinagem-e-area-externa/refletor-externo" },
            { title: "Banco de jardim", href: "/categorias/jardinagem-e-area-externa/banco-de-jardim" },
            { title: "Fonte decorativa", href: "/categorias/jardinagem-e-area-externa/fonte-decorativa" },
            { title: "Cachepot", href: "/categorias/jardinagem-e-area-externa/cachepot" },
            { title: "Limitador de jardim", href: "/categorias/jardinagem-e-area-externa/limitador-de-jardim" },
            { title: "Substrato", href: "/categorias/jardinagem-e-area-externa/substrato" },
            { title: "Argila expandida", href: "/categorias/jardinagem-e-area-externa/argila-expandida" },
            { title: "Irrigador", href: "/categorias/jardinagem-e-area-externa/irrigador" },
            { title: "Carrinho de jardim", href: "/categorias/jardinagem-e-area-externa/carrinho-de-jardim" },
            { title: "Tela de sombreamento", href: "/categorias/jardinagem-e-area-externa/tela-de-sombreamento" },
            { title: "Ombrelone", href: "/categorias/jardinagem-e-area-externa/ombrelone" },
            { title: "Churrasqueira externa", href: "/categorias/jardinagem-e-area-externa/churrasqueira-externa" },
        ],
    },
    {
        title: "Segurança e Proteção",
        subcategories: [
            { title: "Cadeado", href: "/categorias/seguranca-e-protecao/cadeado" },
            { title: "Fechadura reforçada", href: "/categorias/seguranca-e-protecao/fechadura-reforcada" },
            { title: "Trava de porta", href: "/categorias/seguranca-e-protecao/trava-de-porta" },
            { title: "Grade de proteção", href: "/categorias/seguranca-e-protecao/grade-de-protecao" },
            { title: "Concertina", href: "/categorias/seguranca-e-protecao/concertina" },
            { title: "Arame farpado", href: "/categorias/seguranca-e-protecao/arame-farpado" },
            { title: "Tela de proteção", href: "/categorias/seguranca-e-protecao/tela-de-protecao" },
            { title: "Câmera de segurança", href: "/categorias/seguranca-e-protecao/camera-de-seguranca" },
            { title: "Interfone", href: "/categorias/seguranca-e-protecao/interfone" },
            { title: "Vídeo porteiro", href: "/categorias/seguranca-e-protecao/video-porteiro" },
            { title: "Sensor de presença", href: "/categorias/seguranca-e-protecao/sensor-de-presenca" },
            { title: "Alarme", href: "/categorias/seguranca-e-protecao/alarme" },
            { title: "Extintor", href: "/categorias/seguranca-e-protecao/extintor" },
            { title: "Placa de sinalização", href: "/categorias/seguranca-e-protecao/placa-de-sinalizacao" },
            { title: "Corrimão", href: "/categorias/seguranca-e-protecao/corrimao" },
            { title: "Barra de apoio", href: "/categorias/seguranca-e-protecao/barra-de-apoio" },
            { title: "Fita antiderrapante", href: "/categorias/seguranca-e-protecao/fita-antiderrapante" },
            { title: "Capacete", href: "/categorias/seguranca-e-protecao/capacete" },
            { title: "Luva de proteção", href: "/categorias/seguranca-e-protecao/luva-de-protecao" },
            { title: "Óculos de proteção", href: "/categorias/seguranca-e-protecao/oculos-de-protecao" },
            { title: "Botina de segurança", href: "/categorias/seguranca-e-protecao/botina-de-seguranca" },
            { title: "Protetor auricular", href: "/categorias/seguranca-e-protecao/protetor-auricular" },
            { title: "Máscara respiratória", href: "/categorias/seguranca-e-protecao/mascara-respiratoria" },
            { title: "Cone de sinalização", href: "/categorias/seguranca-e-protecao/cone-de-sinalizacao" },
            { title: "Faixa zebrada", href: "/categorias/seguranca-e-protecao/faixa-zebrada" },
            { title: "Sinalizador luminoso", href: "/categorias/seguranca-e-protecao/sinalizador-luminoso" },
            { title: "Trava portão", href: "/categorias/seguranca-e-protecao/trava-portao" },
            { title: "Mola de portão", href: "/categorias/seguranca-e-protecao/mola-de-portao" },
            { title: "Fecho de segurança", href: "/categorias/seguranca-e-protecao/fecho-de-seguranca" },
            { title: "Kit EPI", href: "/categorias/seguranca-e-protecao/kit-epi" },
        ],
    },
    {
        title: "Organização e Armazenamento",
        subcategories: [
            { title: "Estante metálica", href: "/categorias/organizacao-e-armazenamento/estante-metalica" },
            { title: "Prateleira", href: "/categorias/organizacao-e-armazenamento/prateleira" },
            { title: "Nicho", href: "/categorias/organizacao-e-armazenamento/nicho" },
            { title: "Armário multiuso", href: "/categorias/organizacao-e-armazenamento/armario-multiuso" },
            { title: "Caixa organizadora", href: "/categorias/organizacao-e-armazenamento/caixa-organizadora" },
            { title: "Gaveteiro", href: "/categorias/organizacao-e-armazenamento/gaveteiro" },
            { title: "Painel para ferramentas", href: "/categorias/organizacao-e-armazenamento/painel-para-ferramentas" },
            { title: "Suporte para ferramentas", href: "/categorias/organizacao-e-armazenamento/suporte-para-ferramentas" },
            { title: "Gancho organizador", href: "/categorias/organizacao-e-armazenamento/gancho-organizador" },
            { title: "Porta objetos", href: "/categorias/organizacao-e-armazenamento/porta-objetos" },
            { title: "Sapateira", href: "/categorias/organizacao-e-armazenamento/sapateira" },
            { title: "Cabideiro", href: "/categorias/organizacao-e-armazenamento/cabideiro" },
            { title: "Cesto organizador", href: "/categorias/organizacao-e-armazenamento/cesto-organizador" },
            { title: "Organizador de parede", href: "/categorias/organizacao-e-armazenamento/organizador-de-parede" },
            { title: "Racks utilitários", href: "/categorias/organizacao-e-armazenamento/racks-utilitarios" },
            { title: "Armário para lavanderia", href: "/categorias/organizacao-e-armazenamento/armario-para-lavanderia" },
            { title: "Organizador de cozinha", href: "/categorias/organizacao-e-armazenamento/organizador-de-cozinha" },
            { title: "Organizador de banheiro", href: "/categorias/organizacao-e-armazenamento/organizador-de-banheiro" },
            { title: "Baú plástico", href: "/categorias/organizacao-e-armazenamento/bau-plastico" },
            { title: "Caixa plástica", href: "/categorias/organizacao-e-armazenamento/caixa-plastica" },
            { title: "Maleta organizadora", href: "/categorias/organizacao-e-armazenamento/maleta-organizadora" },
            { title: "Separador de prateleira", href: "/categorias/organizacao-e-armazenamento/separador-de-prateleira" },
            { title: "Carrinho organizador", href: "/categorias/organizacao-e-armazenamento/carrinho-organizador" },
            { title: "Suporte suspenso", href: "/categorias/organizacao-e-armazenamento/suporte-suspenso" },
            { title: "Prateleira modular", href: "/categorias/organizacao-e-armazenamento/prateleira-modular" },
            { title: "Estante de PVC", href: "/categorias/organizacao-e-armazenamento/estante-de-pvc" },
            { title: "Estante de madeira", href: "/categorias/organizacao-e-armazenamento/estante-de-madeira" },
            { title: "Caixa para ferramentas", href: "/categorias/organizacao-e-armazenamento/caixa-para-ferramentas" },
            { title: "Armário de oficina", href: "/categorias/organizacao-e-armazenamento/armario-de-oficina" },
            { title: "Organizador multiuso", href: "/categorias/organizacao-e-armazenamento/organizador-multiuso" },
        ],
    },
    {
        title: "Decoração e Acabamento",
        subcategories: [
            { title: "Espelho decorativo", href: "/categorias/decoracao-e-acabamento/espelho-decorativo" },
            { title: "Moldura", href: "/categorias/decoracao-e-acabamento/moldura" },
            { title: "Rodapé", href: "/categorias/decoracao-e-acabamento/rodape" },
            { title: "Roda teto", href: "/categorias/decoracao-e-acabamento/roda-teto" },
            { title: "Boiserie", href: "/categorias/decoracao-e-acabamento/boiserie" },
            { title: "Painel ripado", href: "/categorias/decoracao-e-acabamento/painel-ripado" },
            { title: "Papel de parede", href: "/categorias/decoracao-e-acabamento/papel-de-parede" },
            { title: "Adesivo decorativo", href: "/categorias/decoracao-e-acabamento/adesivo-decorativo" },
            { title: "Placa 3D", href: "/categorias/decoracao-e-acabamento/placa-3d" },
            { title: "Nicho decorativo", href: "/categorias/decoracao-e-acabamento/nicho-decorativo" },
            { title: "Cortineiro", href: "/categorias/decoracao-e-acabamento/cortineiro" },
            { title: "Cortina", href: "/categorias/decoracao-e-acabamento/cortina" },
            { title: "Persiana", href: "/categorias/decoracao-e-acabamento/persiana" },
            { title: "Tapete", href: "/categorias/decoracao-e-acabamento/tapete" },
            { title: "Capacho", href: "/categorias/decoracao-e-acabamento/capacho" },
            { title: "Quadro decorativo", href: "/categorias/decoracao-e-acabamento/quadro-decorativo" },
            { title: "Suporte para cortina", href: "/categorias/decoracao-e-acabamento/suporte-para-cortina" },
            { title: "Varão", href: "/categorias/decoracao-e-acabamento/varao" },
            { title: "Trilho para cortina", href: "/categorias/decoracao-e-acabamento/trilho-para-cortina" },
            { title: "Revestimento decorativo", href: "/categorias/decoracao-e-acabamento/revestimento-decorativo" },
            { title: "Pedra decorativa", href: "/categorias/decoracao-e-acabamento/pedra-decorativa" },
            { title: "Tijolinho decorativo", href: "/categorias/decoracao-e-acabamento/tijolinho-decorativo" },
            { title: "Perfil de acabamento", href: "/categorias/decoracao-e-acabamento/perfil-de-acabamento" },
            { title: "Cantoneira de acabamento", href: "/categorias/decoracao-e-acabamento/cantoneira-de-acabamento" },
            { title: "Soleira", href: "/categorias/decoracao-e-acabamento/soleira" },
            { title: "Peitoril", href: "/categorias/decoracao-e-acabamento/peitoril" },
            { title: "Acabamento para piso", href: "/categorias/decoracao-e-acabamento/acabamento-para-piso" },
            { title: "Friso decorativo", href: "/categorias/decoracao-e-acabamento/friso-decorativo" },
            { title: "Objetos decorativos", href: "/categorias/decoracao-e-acabamento/objetos-decorativos" },
            { title: "Painel decorativo", href: "/categorias/decoracao-e-acabamento/painel-decorativo" },
        ],
    },
    {
        title: "Máquinas e Equipamentos",
        subcategories: [
            { title: "Betoneira", href: "/categorias/maquinas-e-equipamentos/betoneira" },
            { title: "Compactador de solo", href: "/categorias/maquinas-e-equipamentos/compactador-de-solo" },
            { title: "Gerador", href: "/categorias/maquinas-e-equipamentos/gerador" },
            { title: "Compressor de ar", href: "/categorias/maquinas-e-equipamentos/compressor-de-ar" },
            { title: "Lavadora de alta pressão", href: "/categorias/maquinas-e-equipamentos/lavadora-de-alta-pressao" },
            { title: "Bomba periférica", href: "/categorias/maquinas-e-equipamentos/bomba-periferica" },
            { title: "Bomba submersa", href: "/categorias/maquinas-e-equipamentos/bomba-submersa" },
            { title: "Motobomba", href: "/categorias/maquinas-e-equipamentos/motobomba" },
            { title: "Serra de bancada", href: "/categorias/maquinas-e-equipamentos/serra-de-bancada" },
            { title: "Policorte", href: "/categorias/maquinas-e-equipamentos/policorte" },
            { title: "Cortadora de piso", href: "/categorias/maquinas-e-equipamentos/cortadora-de-piso" },
            { title: "Rompedor", href: "/categorias/maquinas-e-equipamentos/rompedor" },
            { title: "Martelete profissional", href: "/categorias/maquinas-e-equipamentos/martelete-profissional" },
            { title: "Perfurador de solo", href: "/categorias/maquinas-e-equipamentos/perfurador-de-solo" },
            { title: "Misturador de argamassa", href: "/categorias/maquinas-e-equipamentos/misturador-de-argamassa" },
            { title: "Vibrador de concreto", href: "/categorias/maquinas-e-equipamentos/vibrador-de-concreto" },
            { title: "Andaime", href: "/categorias/maquinas-e-equipamentos/andaime" },
            { title: "Escada extensiva", href: "/categorias/maquinas-e-equipamentos/escada-extensiva" },
            { title: "Escada articulada", href: "/categorias/maquinas-e-equipamentos/escada-articulada" },
            { title: "Escora metálica", href: "/categorias/maquinas-e-equipamentos/escora-metalica" },
            { title: "Carrinho plataforma", href: "/categorias/maquinas-e-equipamentos/carrinho-plataforma" },
            { title: "Paleteira manual", href: "/categorias/maquinas-e-equipamentos/paleteira-manual" },
            { title: "Guincho manual", href: "/categorias/maquinas-e-equipamentos/guincho-manual" },
            { title: "Talha", href: "/categorias/maquinas-e-equipamentos/talha" },
            { title: "Roçadeira", href: "/categorias/maquinas-e-equipamentos/rocadeira" },
            { title: "Motosserra", href: "/categorias/maquinas-e-equipamentos/motosserra" },
            { title: "Aparador de cerca viva", href: "/categorias/maquinas-e-equipamentos/aparador-de-cerca-viva" },
            { title: "Aspirador industrial", href: "/categorias/maquinas-e-equipamentos/aspirador-industrial" },
            { title: "Kit de manutenção", href: "/categorias/maquinas-e-equipamentos/kit-de-manutencao" },
            { title: "Peças e acessórios", href: "/categorias/maquinas-e-equipamentos/pecas-e-acessorios" },
        ],
    },
]
